import 'package:flutter/material.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedContentWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedAddAdminWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedSettingWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedCategoryWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedPanelsWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedFrame17Widget13.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedPushnotificationWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedBipersoncircleWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedAntdesignbellfilledWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle1Widget57.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedHomeWidget47.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedIITmandi14Widget7.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedAntdesignhomefilledWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedCarbonoverflowmenuverticalWidget43.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedResponseWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedCarbonaddfilledWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedIcbaselinecameraWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedCategoryWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedBytesizemenuWidget43.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox93widget/generated/GeneratedRectangle40Widget.dart';

/* Frame iPhone 11 Pro / X - 93
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX93Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 161.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedIcbaselinecameraWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle42Widget(),
              ),
              Positioned(
                left: 303.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle45Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 25.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 177.0,
                right: 301.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedHomeWidget47(),
              ),
              Positioned(
                left: 165.0,
                top: 175.0,
                right: 154.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedCategoryWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 175.0,
                right: 226.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedPanelsWidget(),
              ),
              Positioned(
                left: 245.0,
                top: 176.0,
                right: 95.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 114.0,
                top: 216.0,
                right: 199.0,
                bottom: null,
                width: null,
                height: 11.0,
                child: GeneratedAddAdminWidget(),
              ),
              Positioned(
                left: 314.0,
                top: 175.0,
                right: 7.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedSettingWidget(),
              ),
              Positioned(
                left: 219.0,
                top: 216.0,
                right: 102.0,
                bottom: null,
                width: null,
                height: 14.0,
                child: GeneratedLogoutWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 342.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 91.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 91.0,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 91.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 91.0,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 367.0,
                right: 94.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedCategoryWidget1(),
              ),
              Positioned(
                left: 227.0,
                top: 491.0,
                right: 83.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedResponseWidget(),
              ),
              Positioned(
                left: 69.0,
                top: 364.0,
                right: 241.0,
                bottom: null,
                width: null,
                height: 16.0,
                child: GeneratedContentWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 480.0,
                right: 224.0,
                bottom: null,
                width: null,
                height: 13.0,
                child: GeneratedPushnotificationWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedAntdesignhomefilledWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedCarbonaddfilledWidget(),
              ),
              Positioned(
                left: 297.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedBipersoncircleWidget(),
              ),
              Positioned(
                left: 228.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedAntdesignbellfilledWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget57(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget43()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -361.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget43()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -356.50,
                    z: 0,
                    child: GeneratedIITmandi14Widget7()),
              ),
              Positioned(
                left: -4.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 357.0002136230469,
                height: 22.11505126953125,
                child: GeneratedFrame17Widget13(),
              )
            ]),
      ),
    ));
  }
}
