import 'package:flutter/material.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedIITmandi15Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedRectangle2Widget23.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedIITmandi16Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedCarbonoverflowmenuverticalWidget42.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedBytesizemenuWidget40.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedThankyouforyourfeedbackWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedCarbonoverflowmenuverticalWidget41.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedIITmandi14Widget6.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedFrame17Widget12.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedRectangle1Widget54.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedCarbonoverflowmenuverticalWidget40.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedTeenyiconsmessageticksolidWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedBytesizemenuWidget42.dart';
import 'package:flutterapp/tihapp/generatediphone11prox85widget/generated/GeneratedBytesizemenuWidget41.dart';

/* Frame iPhone 11 Pro / X - 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX85Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 129.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 116.0,
                child: GeneratedTeenyiconsmessageticksolidWidget(),
              ),
              Positioned(
                left: 97.0,
                top: 358.0,
                right: 95.0,
                bottom: null,
                width: null,
                height: 18.0,
                child: GeneratedThankyouforyourfeedbackWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.001,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget54(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget40()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -361.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget40()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -356.50,
                    z: 0,
                    child: GeneratedIITmandi14Widget6()),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle2Widget23(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget41()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -361.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget41()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -356.50,
                    z: 0,
                    child: GeneratedIITmandi15Widget1()),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle3Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget42()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -361.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget42()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -356.50,
                    z: 0,
                    child: GeneratedIITmandi16Widget1()),
              ),
              Positioned(
                left: -4.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 357.0002136230469,
                height: 22.11505126953125,
                child: GeneratedFrame17Widget12(),
              )
            ]),
      ),
    ));
  }
}
