import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedIITmandi14Widget9.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedUploadImageWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedEnterdescriptionWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedFrame17Widget15.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedSubmitWidget6.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedBxsimageaddWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedCarbonoverflowmenuverticalWidget45.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedBytesizemenuWidget45.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedEnterTitleWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedDescriptionWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedRectangle1Widget59.dart';
import 'package:flutterapp/tihapp/generatediphone11prox94widget/generated/GeneratedTitleWidget.dart';

/* Frame iPhone 11 Pro / X - 94
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX94Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1161.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1161.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 136.0,
                              child: GeneratedRectangle55Widget(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 169.0,
                              right: 116.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedTitleWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 278.0,
                              right: 141.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedUploadImageWidget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 463.0,
                              right: 123.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedDescriptionWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 44.0,
                              child: GeneratedRectangle53Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 136.0,
                              child: GeneratedRectangle54Widget(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 659.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 25.0,
                              child: GeneratedRectangle56Widget(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedBxsimageaddWidget(),
                            ),
                            Positioned(
                              left: 247.0,
                              top: 661.0,
                              right: 54.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedSubmitWidget6(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 210.0,
                              right: 107.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedEnterTitleWidget(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 515.0,
                              right: 128.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedEnterdescriptionWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0826666666666667;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget59(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -529.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget45()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -535.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget45()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -531.00,
                                  z: 0,
                                  child: GeneratedIITmandi14Widget9()),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame17Widget15(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
