import 'package:flutter/material.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedRectangle1Widget61.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedCarbonoverflowmenuverticalWidget47.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedCharmuploadWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedAntdesignhomefilledWidget2.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedBipersoncircleWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedBytesizemenuWidget47.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedCarbonaddfilledWidget2.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedFrame17Widget17.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedAntdesignbellfilledWidget2.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedIcbaselinecameraWidget2.dart';
import 'package:flutterapp/tihapp/generatediphone11prox95widget/generated/GeneratedIITmandi14Widget11.dart';

/* Frame iPhone 11 Pro / X - 95
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX95Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 172.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedCharmuploadWidget(),
              ),
              Positioned(
                left: 167.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedIcbaselinecameraWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedAntdesignhomefilledWidget2(),
              ),
              Positioned(
                left: 96.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedCarbonaddfilledWidget2(),
              ),
              Positioned(
                left: 303.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedBipersoncircleWidget2(),
              ),
              Positioned(
                left: 234.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 43.0,
                child: GeneratedAntdesignbellfilledWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 92.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0826666666666667;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.016,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedRectangle1Widget61(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -355.00,
                    z: 0,
                    child: GeneratedBytesizemenuWidget47()),
              ),
              Positioned(
                left: null,
                top: null,
                right: 11.0,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -361.00,
                    z: 0,
                    child: GeneratedCarbonoverflowmenuverticalWidget47()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 82.0,
                height: 65.0,
                child: TransformHelper.translate(
                    x: -2.50,
                    y: -356.50,
                    z: 0,
                    child: GeneratedIITmandi14Widget11()),
              ),
              Positioned(
                left: -4.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 357.0002136230469,
                height: 22.11505126953125,
                child: GeneratedFrame17Widget17(),
              )
            ]),
      ),
    ));
  }
}
