import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle53Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedSubmitWidget7.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedBytesizemenuWidget46.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedCarbonoverflowmenuverticalWidget46.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedDescriptionWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedIITmandi14Widget10.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle54Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedEnterTitleWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle1Widget60.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedFrame17Widget16.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedTitleWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedUploadImageWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedSelectfromfilesWidget.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedBxsimageaddWidget1.dart';
import 'package:flutterapp/tihapp/generatediphone11prox114widget/generated/GeneratedEnterdescriptionWidget1.dart';

/* Frame iPhone 11 Pro / X - 114
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX114Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1253.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1253.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 136.0,
                              child: GeneratedRectangle55Widget1(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 169.0,
                              right: 116.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedTitleWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 278.0,
                              right: 141.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedUploadImageWidget1(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 463.0,
                              right: 123.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedDescriptionWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 197.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 44.0,
                              child: GeneratedRectangle53Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 136.0,
                              child: GeneratedRectangle54Widget1(),
                            ),
                            Positioned(
                              left: 232.0,
                              top: 659.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 25.0,
                              child: GeneratedRectangle56Widget1(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 356.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedBxsimageaddWidget1(),
                            ),
                            Positioned(
                              left: 247.0,
                              top: 661.0,
                              right: 54.0,
                              bottom: null,
                              width: null,
                              height: 33.0,
                              child: GeneratedSubmitWidget7(),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 107.0,
                              child: GeneratedRectangle57Widget(),
                            ),
                            Positioned(
                              left: 97.0,
                              top: 368.0,
                              right: 84.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedSelectfromfilesWidget(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 515.0,
                              right: 128.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedEnterdescriptionWidget1(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 210.0,
                              right: 107.0,
                              bottom: null,
                              width: null,
                              height: 30.0,
                              child: GeneratedEnterTitleWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -5.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 92.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 1.0826666666666667;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * -0.016,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedRectangle1Widget60(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 24.0,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 36.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -575.50,
                                  z: 0,
                                  child: GeneratedBytesizemenuWidget46()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 11.0,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -581.50,
                                  z: 0,
                                  child:
                                      GeneratedCarbonoverflowmenuverticalWidget46()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 65.0,
                              child: TransformHelper.translate(
                                  x: -2.50,
                                  y: -577.00,
                                  z: 0,
                                  child: GeneratedIITmandi14Widget10()),
                            ),
                            Positioned(
                              left: -4.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 357.0002136230469,
                              height: 22.11505126953125,
                              child: GeneratedFrame17Widget16(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
