import 'package:flutter/material.dart';

/* Rectangle IDAPT Hub Foundation, Varanasi 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIDAPTHubFoundationVaranasi1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 61.68367385864258,
      height: 65.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/16af0d8166cd95261197c7b6f3e5beeeb3c19cf5.png",
          color: null,
          fit: BoxFit.cover,
          width: 61.68367385864258,
          height: 65.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
