import 'package:flutter/material.dart';
import 'package:flutterapp/tihapp/generatedframe17widget22/generated/GeneratedJoinWidget49.dart';

/* Frame Frame 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame17Widget22 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 357.0002136230469,
        height: 22.11505699157715,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 302.76544189453125,
                top: -1.1368683772161603e-13,
                right: null,
                bottom: null,
                width: 56.23455047607422,
                height: 17.26992130279541,
                child: GeneratedJoinWidget49(),
              )
            ]),
      ),
    ));
  }
}
